/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { BaseResource, CloudError } from "ms-rest-azure-js";

export { BaseResource, CloudError };


/**
 * @interface
 * An interface representing FeatureProperties.
 * Information about feature.
 *
 */
export interface FeatureProperties {
  /**
   * @member {string} [state] The registration state of the feature for the
   * subscription.
   */
  state?: string;
}

/**
 * @interface
 * An interface representing FeatureResult.
 * Previewed feature information.
 *
 */
export interface FeatureResult {
  /**
   * @member {string} [name] The name of the feature.
   */
  name?: string;
  /**
   * @member {FeatureProperties} [properties] Properties of the previewed
   * feature.
   */
  properties?: FeatureProperties;
  /**
   * @member {string} [id] The resource ID of the feature.
   */
  id?: string;
  /**
   * @member {string} [type] The resource type of the feature.
   */
  type?: string;
}


/**
 * @interface
 * An interface representing the FeatureOperationsListResult.
 * List of previewed features.
 *
 * @extends Array<FeatureResult>
 */
export interface FeatureOperationsListResult extends Array<FeatureResult> {
  /**
   * @member {string} [nextLink] The URL to use for getting the next set of
   * results.
   */
  nextLink?: string;
}
