/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

export {
  RecordSet,
  ARecord,
  AaaaRecord,
  MxRecord,
  NsRecord,
  PtrRecord,
  SrvRecord,
  TxtRecord,
  CnameRecord,
  SoaRecord,
  CloudError,
  RecordSetListResult
} from "../models/mappers";

